### PR TITLE
fix: Update install_hybrid_cluster.sh

### LINKED ISSUE #678: Adding more APIs and role binding to the prerequisite
While reproducing a case, I noticed that customers using this public document to create GKE on bare metal are likely to encounter errors due to some missing prerequisites..

Under the list on APIs to be enable we need to include the following :

    iam.googleapis.com 
    kubernetesmetadata.googleapis.com 
   
Also under the role bindings, we need to include the following :

`gcloud projects add-iam-policy-binding PROJECT_ID \
    --member="serviceAccount:baremetal-gcr@$PROJECT_ID.iam.gserviceaccount.com" \
    --role="roles/kubernetesmetadata.publisher"`

### PR DESCRIPTION
**Pull request by gavi0231**
fix: Add more APIs and role binding to script to address prerequisites #678 

Update the script to address prerequisite changes from the GDC (software only) on bare metal minor release 1.29:

* Enable additional services/APIs for the GCP project
* Grant additional IAM roles to the baremetal-gcr service account

#### Description
Script updates to add more APIs and IAM roles per product updates from 1.29 minor release.

#### Change summary
Add the following APIs to the gcloud services enable command:

- compute.googleapis.com
- gkeonprem.googleapis.com
- iam.googleapis.com
- kubernetesmetadata.googleapis.com 

Add the following commands to grant additional IAM roles to the baremetal-gcr service account:

```
gcloud projects add-iam-policy-binding "$PROJECT_ID" \
    --member="serviceAccount:baremetal-gcr@$PROJECT_ID.iam.gserviceaccount.com" \
    --role="roles/kubernetesmetadata.publisher" \
    --no-user-output-enabled 

gcloud projects add-iam-policy-binding "$PROJECT_ID" \
  --member="serviceAccount:baremetal-gcr@$PROJECT_ID.iam.gserviceaccount.com" \
  --role="roles/monitoring.viewer" \
  --no-user-output-enabled

gcloud projects add-iam-policy-binding "$PROJECT_ID" \
  --member="serviceAccount:baremetal-gcr@$PROJECT_ID.iam.gserviceaccount.com" \
  --role="roles/serviceusage.serviceUsageViewer" \
  --no-user-output-enabled
```

#### Related PRs/Issues
- PR 679

### CODE REVIEW

**Comment by NimJay** [comment]
The error we're encountering in [the integration tests](https://console.cloud.google.com/cloud-build/builds/2118a7af-2cdc-4ab1-903a-f88c1f812fdc;step=6?e=13803378&inv=1&invt=AbaoAQ&mods=notebooks_use_staging_api&project=cloud-foundation-cicd):
```
Error creating instance: googleapi: Error 404: The resource 'projects/ci-abm-109e4ad9-7ada/zones/us-central1-a/acceleratorTypes/nvidia-tesla-k80' was not found, notFound
```
seems unrelated to the changes here.
I believe it was fixed via https://github.com/GoogleCloudPlatform/anthos-samples/pull/691/files#r1734756391.

I will merge main the source branch.

**Review by apeabody — APPROVED** [review]
Thanks @gavi0231!

**Pull request merged**
