### PR TITLE
fix: missing services needed for setup

### LINKED ISSUE #158: Missing API  and roles required during ABM installation and
During the installation of latest version I found the following services weren't enabled by Terraform:
-  "anthosaudit.googleapis.com",
 - "opsconfigmonitoring.googleapis.com"

moreover the service account created doesn't have the following permission needed:
roles/opsconfigmonitoring.resourceMetadata.writer

Fixing those the installation of ABM 1.10 has been completed.

### PR DESCRIPTION
**Pull request by miticojo**
#### Description
- Fix missing role permission and API needed during ABM installation 

#### Change summary
- Additional role _opsconfigmonitoring.resourceMetadata.writer_
- Additional API   anthosaudit.googleapis.com
- Additional API  opsconfigmonitoring.googleapis.com

#### Related PRs/Issues
- Fix issue #158

### CODE REVIEW

**Review by Shabirmean — DISMISSED** [review]

**Comment by Shabirmean** [comment]
@miticojo - are these additional roles required for a specific use-case? As I see the other PRs seems to be building without an issue. So I am assuming what we currently have is sufficient for the basic scenario!

**Comment by miticojo** [comment]
bmctl fails installation because service requirements are not enabled:
https://cloud.google.com/anthos/clusters/docs/bare-metal/1.8/installing/install-prereq#project_prerequisites

In the doc you can see `opsconfigmonitoring.googleapis.com` is listed while `anthosaudit.googleapis.com` is not. 
As far as I understood starting from 1.9 bmctl has installation pre-checks that verify the following services:
- anthos.googleapis.com
- anthosaudit.googleapis.com
- anthosgke.googleapis.com
- cloudresourcemanager.googleapis.com
- gkeconnect.googleapis.com
- gkehub.googleapis.com
- iam.googleapis.com
- opsconfigmonitoring.googleapis.com
- logging.googleapis.com
- monitoring.googleapis.com
- stackdriver.googleapis.com

You might ask @jeanjin to double check.

My suggestion: if we are unable to track required services and prepare the project through Terraform the best suggestion would be to integrate the [doc](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest) with the list of services needed.

**Comment by Shabirmean** [comment]
> bmctl fails installation because service requirements are not enabled: https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/installing/install-prereq#project_prerequisites
> 
> In the doc you can see `opsconfigmonitoring.googleapis.com` and `anthosaudit.googleapis.com` are listed. As far as I understood starting from 1.9 bmctl has installation pre-checks that verify the following services:
> 
> * anthos.googleapis.com
> * anthosaudit.googleapis.com
> * anthosgke.googleapis.com
> * cloudresourcemanager.googleapis.com
> * gkeconnect.googleapis.com
> * gkehub.googleapis.com
> * iam.googleapis.com
> * opsconfigmonitoring.googleapis.com
> * logging.googleapis.com
> * monitoring.googleapis.com
> * stackdriver.googleapis.com
> 
> My suggestion: if we are unable to track required services and prepare the project through Terraform the best suggestion would be to integrate the [doc](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest) with the list of services needed.

I see. Thank you very much @miticojo for the updates. We will try to somehow find parity with these changes or capture them soon when things update.

**Comment by Shabirmean** [comment]
@miticojo Issue https://github.com/GoogleCloudPlatform/anthos-samples/issues/194 tracks the needs to more integration tests to ensure issues like this doesn't happen again and PR https://github.com/GoogleCloudPlatform/anthos-samples/pull/193 addresses it

**Pull request merged**
