### PR TITLE
feat: Uploading snapshot to GCS using create_snapshot.py

### LINKED ISSUE #80: Snapshot Upload Capability to Google Cloud Storage
To ease use of collecting Anthos Clusters and uploading of snapshots created from create_snapshot.py provide functionality to upload snapshots to a Google Cloud Storage bucket.

Assuming that a user has the Google Cloud SDK the script should allow for specifying a bucket name and a service account key to upload the snapshot tar file.

Added arguments:
--upload-to <bucket name>
--service-account-key-file <path to service account key file>

### PR DESCRIPTION
**Pull request by jdcarbeck**
#### Description
- This pull request add functionality to upload to a Google Cloud Storage bucket by allowing the user to specify a bucket name and a key file for a service account. Error handling for bucket name and service account permissions before snapshot is created. After the snapshot it is uploaded to the GCS bucket specified in the arguments

#### Change summary
Added Arguments:
--upload-to : name of bucket that should be created or used for uploading snapshot
--service-account-key-file : key file used is gcloud auth activiate-service-account

Methods:
upload_preflight(bucket: str): Authenticates as service account, checks if bucket exists using gsutil ls -b gs://BUCKET_NAME, if this fails a bucket of that name is created

upload_file(bucket:str, snap_file: str): uploads file to bucket

run_gsutil_cmd(command: str): Runs gsutil/gcloud commands in a shell environment returning the return code of the command and the output (stdout/stderr)

### CODE REVIEW

**Comment by bourgeoisor** [comment]
I've approved the workflows to run. Note that some checks are failing and will have to be resolved before we can merge this PR.

**Comment by NimJay** [comment]
## 2 checks are failing:

### 1. gcloud: Google Compute Instances configuration (1 failed)
Judging from the [Cloud Build logs](https://pantheon.corp.google.com/cloud-build/builds/6ba282b0-a873-4e40-be73-ecb8551ef05d;step=7?project=cloud-foundation-cicd), it seems like [`run_initialization_checks.sh`](https://github.com/GoogleCloudPlatform/anthos-samples/blob/4c8a87a9b989d7246fcb2e93097cda281ec5831b/anthos-bm-gcp-terraform/resources/run_initialization_checks.sh) is failing somewhere.
But I am not sure where `run_initialization_checks.sh`'s logs can be found.
I'm hoping @Shabirmean can help us decipher this when he gets back from his break.

### 2. Python Linting
```
./troubleshooting/create_snapshot.py:94:80: E501 line too long (96 > 79 characters)
./troubleshooting/create_snapshot.py:97:80: E501 line too long (99 > 79 characters)
./troubleshooting/create_snapshot.py:102:80: E501 line too long (87 > 79 characters)
./troubleshooting/create_snapshot.py:103:80: E501 line too long (85 > 79 characters)
./troubleshooting/create_snapshot.py:109:1: E302 expected 2 blank lines, found 1
./troubleshooting/create_snapshot.py:109:32: E999 SyntaxError: invalid syntax
./troubleshooting/create_snapshot.py:110:80: E501 line too long (86 > 79 characters)
./troubleshooting/create_snapshot.py:117:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:118:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:119:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:120:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:124:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:129:11: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:130:11: E114 indentation is not a multiple of 4 (comment)
./troubleshooting/create_snapshot.py:131:11: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:133:11: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:134:11: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:135:11: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:137:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:138:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:139:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:148:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:149:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:150:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:156:3: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:159:7: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:161:3: E111 indentation is not a multiple of 4
./troubleshooting/create_snapshot.py:277:1: E305 expected 2 blank lines after class or function definition, found 1
```

@jdcarbeck, I'm sure you can easily address most of these linting errors (e.g., fixing indentation to multiples of 4). :)

But I am a bit conflicted about the 79-character line restriction.
There's a debate around the 79 character limit in [this Stackoverflow post](https://stackoverflow.com/questions/88942/why-does-pep-8-specify-a-maximum-line-length-of-79-characters).
John, if you'd prefer to extend the line limit to 100 characters (which seems reasonable in 2021 😅), we can look into changing that — and see if it's doable in a clean manner.

**Comment by jdcarbeck** [comment]
Sorry my mistake there on the linter. I’ll update the pull request in the next day

**Comment by jdcarbeck** [comment]
Linting errors should be fixed now

**Comment by Shabirmean** [comment]
Thank you @jdcarbeck for fixing them. 

@m-strzelczyk we (`anthos-dpes`) will review it for code correctness. However, as the original author, can you review the changes for anything else that needs to be considered??

**Review by m-strzelczyk — APPROVED** [review]
LGTM

**Pull request merged**
