### PR TITLE
fix: support re-running the GCE-TF scripts to create two ABM clusters in same project

### LINKED ISSUE #14: Subsequent runs of the TF script for ABM setup with new variables conflict
### Issue:
- With the current setup if we run the ABM on GCE TF scripts twice with different cluster names the second one conflicts with the first

### What should happen:
- Subsequent runs with different TF variables should produce 2 different clusters

### Potential fix:
- Prefix the resources with the cluster_name from the variables
- Take in a separate prefix var to use with each resource name specific to a cluster

### PR DESCRIPTION
**Pull request by Shabirmean**
#### Description
- The sample for [installing ABM on GCE using Terraform](https://github.com/GoogleCloudPlatform/anthos-samples/tree/master/anthos-bm-gcp-terraform) cannot be run twice against the same project to create to 2 ABM clusters with different sets of VMs
- The reason for this is that the VM names between the subsequent runs will clash

#### Change summary
- Prefix the GCE VM names with the ABM cluster name _(which is an input variable tot he terraform script)_. This makes sure that the new GCE VMs don't have any clashes. 

#### Related PRs/Issues
- Issue #14
- A [documentation CL](http://cl/408093978) has been opened to update the docs to have the cluster prefix wherever the GCE VM is referred to

#### Testing guidelines
- Follow the steps from [this cloud docs](https://cloud.devsite.corp.google.com/anthos/clusters/docs/bare-metal/latest/try/gce-vms-tf) site to get an Anthos on Baremetal cluster running on GCE VMs
- Now  follow the steps from [this Github readme](https://github.com/GoogleCloudPlatform/anthos-samples/blob/fix-double-run/anthos-bm-gcp-terraform/docs/quickstart.md) to create another ABM cluster on GCE in the same project.
  - When creating the second cluster you have to make sure that you don't run the terraform script from the same git repo that you cloned the first time. This is because that repo will have a `terraform state` from the first run you made. This will lead to terraform just trying to update the existing resources
  - You also must change 2 variables in the [`terraform.tfvars`](https://github.com/GoogleCloudPlatform/anthos-samples/blob/fix-double-run/anthos-bm-gcp-terraform/terraform.tfvars.sample) file the second time so that it doesn't conflict with the first one. 
     - `abm_cluster_id` should be different from what you used the first time
     - `anthos_service_account_name ` should be different from the default one used during the first run. You will not see this variable in the given sample `tfvars` file. This is because the default value for it from [`variable.tf` ](https://github.com/GoogleCloudPlatform/anthos-samples/blob/fix-double-run/anthos-bm-gcp-terraform/variables.tf) was used. To use a different value for this variable just add this variable to your new `terraform.tfvars` file
     - All the other fields in the `tarraform.tfvars` file shall remain the same.

Following the above steps should ideally create 6 GCE VMs and 2 ABM clusters!

### CODE REVIEW

**Comment by ahrarmonsur** [comment]
Encountered some errors while testing, specifically in the "Deploy the hybrid cluster" step.
Documenting the errors here:
https://docs.google.com/document/d/1btav1z_1-yWUNsL9Vc-OoIV58XNxCpWlfd5sK049c3U/edit?resourcekey=0-Gu70jHWS1YZFsilQhxQBag#

**Comment by ahrarmonsur** [comment]
I have tested this PR, successfully creating 2 clusters (with 6 VMs each) with the same set of scripts, modifying only the cluster and service account names.

Things to note:
- when running the command to create the token that will be used to verify the state of the clusters by logging in through GCP, one cannot run it with `sudo`, as the export environment names will not be available in the super-user subshell.
- @Shabirmean, the necessity for uniquely names service account for each cluster is mentioned in the steps to test, but is not specifically signalled anywhere in the repo. Since it appears to be a hard requirement, similar to unique cluster names, perhaps it would be helpful to have an explicit entry for it in the `terraform.tfvars.sample`? This is a nit, and not a blocker for this PR. 

Screenshots (internal)
Clusters: https://screenshot.googleplex.com/9hxWPD6mYdyjnSU.png
VMs: https://screenshot.googleplex.com/7eqCrmDzGKETtEc.png

**Review by ahrarmonsur — APPROVED** [review]
LGTM, left a summary of testing and a (non-blocking) suggestion.

**Comment by Shabirmean** [comment]
> I have tested this PR, successfully creating 2 clusters (with 6 VMs each) with the same set of scripts, modifying only the cluster and service account names.
> 
> Things to note:
> 
> * when running the command to create the token that will be used to verify the state of the clusters by logging in through GCP, one cannot run it with `sudo`, as the export environment names will not be available in the super-user subshell.
> * @Shabirmean, the necessity for uniquely names service account for each cluster is mentioned in the steps to test, but is not specifically signalled anywhere in the repo. Since it appears to be a hard requirement, similar to unique cluster names, perhaps it would be helpful to have an explicit entry for it in the `terraform.tfvars.sample`? This is a nit, and not a blocker for this PR.
> 
> Screenshots (internal) Clusters: https://screenshot.googleplex.com/9hxWPD6mYdyjnSU.png VMs: https://screenshot.googleplex.com/7eqCrmDzGKETtEc.png

Thank you very much for reviewing this PR in detail @ahrarmonsur. To respond to some of the points raised above:

1. Good catch, but `logging in to the cluster` is not directly part of the guide and is pointed to via another set of documentation. Thus, this detail wouldn't be essential related to this PR/guide
2. That's a great point as well. However the PR aims to ensure `1+N` clusters in the same project is something **doable** with the provided scripts. The objective is not to provide steps for more than 1 cluster. The document aims to just cover a 1 cluster case. So I would leave away details of 1+ clusters out of the document.

**Pull request merged**
