### PR TITLE
feat: Add terraform samples for GKE Attached clusters.

### PR DESCRIPTION
**Pull request by hankfreund**
#### Description
Add samples demonstrating use of GKE attached clusters with both AKS and EKS. The samples:
1. create a cluster
2. prepare the cluster for attach
3. attach the cluster as a single Terraform apply step, which has been problematic for users.

### CODE REVIEW

**Comment by Shabirmean** [comment]
@bharathkkb the CI tests are failing given some resource limitations. I think the tests run on the cloud foundation team's CI projects. Do you know who might be able to help Hank here?

```
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        Error: Error waiting for instance to create: The zone 'projects/ci-abm-245d5a28-f04d/zones/us-central1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'.
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        A n1-standard-8 VM instance with 1 nvidia-tesla-k80 accelerator(s) is currently unavailable in the us-central1-a zone. Consider trying your request in the us-central1-c zone(s), which currently has capacity to accommodate your request. Alternatively, you can try your request again with a different VM hardware configuration or at a later time. For more information, see the troubleshooting documentation.
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        Troubleshooting documentation
Step #6 - "converge abm-gce-gpu":        https://cloud.google.com/compute/docs/resource-error
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":          with module.anthos_bm_gcp.module.admin_vm_hosts.module.compute_instance["cluster1-abm-ws0"].google_compute_instance_from_template.compute_instance[0],
Step #6 - "converge abm-gce-gpu":          on .terraform/modules/anthos_bm_gcp.admin_vm_hosts.compute_instance/modules/compute_instance/main.tf line 45, in resource "google_compute_instance_from_template" "compute_instance":
Step #6 - "converge abm-gce-gpu":          45: resource "google_compute_instance_from_template" "compute_instance" {
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        Error: Error waiting for instance to create: The zone 'projects/ci-abm-245d5a28-f04d/zones/us-central1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'.
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        
Step #6 - "converge abm-gce-gpu":        A n1-standard-8 VM instance with 1 nvidia-tesla-k80 accelerator(s) is currently unavailable in the us-central1-a zone. Consider trying your request in the us-central1-c zone(s), which currently has capacity to accommodate your request. Alternatively, you can try your request again with a different VM hardware configuration or at a later time. For more information, see the troubleshooting documentation.
Step #6 - "converge abm-gce-gpu":        
```

**Comment by bharathkkb** [comment]
@Shabirmean it looks like stockout rather than quota? I suggest retrying it in a bit to see if it helps. If not we can ignore the failure or disable the test to unblock PRs.

**Comment by bourgeoisor** [comment]
Re-ran the test and it passed?

**Comment by hankfreund** [comment]
Looks like it is passing again, which is great. @bourgeoisor, as a code owner, can you approve so I can merge?

**Review by bourgeoisor — APPROVED** [review]
Looks good from my end.

**Pull request merged**
