### PR TITLE
feat: [anthos-bm-gcp-terraform] parameterize ABM version

### PR DESCRIPTION
**Pull request by apeabody**
#### Description
- Parameterize ABM version to a single `abm_version` variable rather than hard coded
- Set default `abm_version` to 1.14.1
- Updates the test to use `abm_version` instead of using hard coded

### CODE REVIEW

**Comment by apeabody** [comment]
@Shabirmean - Can you please assist with /gcbrun ?

**Comment by Shabirmean** [comment]
Thank you very much @apeabody for this improvement. This makes it super easy!

**Review by Shabirmean — CHANGES_REQUESTED** [review]
Can we also update the sample [terraform.tfvars.sample](https://github.com/GoogleCloudPlatform/anthos-samples/blob/main/anthos-bm-gcp-terraform/terraform.tfvars.sample) file?

**Comment by Shabirmean** [comment]
Also there is a linting error:

```
In ./anthos-bm-gcp-terraform/resources/init_vm.sh line 171:
  gsutil cp gs://anthos-baremetal-release/bmctl/$ABM_VERSION/linux-amd64/bmctl .
                                                ^----------^ SC2086: Double quote to prevent globbing and word splitting.
```

**Comment by Shabirmean** [comment]
> > Can we also update the sample [terraform.tfvars.sample](https://github.com/GoogleCloudPlatform/anthos-samples/blob/main/anthos-bm-gcp-terraform/terraform.tfvars.sample) file?
> 
> Hi Shabir Mohamed Abdul Samadh - Are you thinking in addition, or instead of, the default value?

I just now saw that you have a default value. I think that is enough, so that we just have one place to update when we do changes.

**Review by Shabirmean — APPROVED** [review]

**Review by Shabirmean — APPROVED** [review]

**Pull request merged**
