### PR TITLE
fix: [anthos-bm-gcp-terraform] enforce min TF per README.md

### LINKED ISSUE #267: feat: [anthos-bm-gcp-terraform] enforce min TF version per README

### PR DESCRIPTION
**Pull request by apeabody**
#### Description
- Add min TF version for [anthos-bm-gcp-terraform] per README.md

### CODE REVIEW

**Comment by Shabirmean** [comment]
@apeabody Thank you for opening this PR. Is this a strict requirement with the current Terraform script? The earlier versions (0.2.0,0.3.0) have been working with 0.14.9 of Terraform as well

**Comment by Shabirmean** [comment]
@apeabody Ahh okay. Makes sense. I didn't realize we had that inconsistency in two places.

**Comment by Shabirmean** [comment]
@apeabody Seems like this change doesn't sit well with [release-please bot](https://github.com/GoogleCloudPlatform/anthos-samples/pull/274/files). Shall we revert this change as before we can merge that release PR?

**Comment by apeabody** [comment]
@Shabirmean That is unexpected.  Yes, I would revert for now as it's not that likely someone is attempting to use a really old version of TF.

**Pull request merged**
