### PR TITLE
process: update the CODEOWNERS file to add the go/onyx-observability team

### PR DESCRIPTION
**Pull request by Shabirmean**
### Fixes.
- Doesn't address any specific issue

#### Description
- The samples specific to GKE observability/monitoring needs to be reviewed by someone from that team.
- There are two samples currently:
    - [/aws-logging-monitoring/](https://github.com/GoogleCloudPlatform/anthos-samples/tree/master/aws-logging-monitoring) 
    - [/attached-logging-monitoring/ ](https://github.com/GoogleCloudPlatform/anthos-samples/tree/master/attached-logging-monitoring)
- The Onyx Team can be [found here](http://go/onyx-observability)

#### Change summary
- Create a new GH team under the `GoogleCloudPlatform` for the [`onyx-observability` team](https://github.com/orgs/GoogleCloudPlatform/teams/onyx-gke-observability/)
- Update the `CODEOWNERS` file to include the `onyx-observability` team to the CODEOWNERS file

#### Notes:
- Currently the GH Team for [`onyx-observability`](https://github.com/orgs/GoogleCloudPlatform/teams/onyx-gke-observability/) only has @rsgowman because the others (@leonzz @rsgowman @courageJ) are not members of the GH Organization `GoogleCloudPlatform`.

- @leonzz, @rsgowman, @courageJ - if you'll can join the `GoogleCloudPlatform` organization by visiting [go/github](https://opensource.corp.google.com/github/), I can add you'll to the team as well

#### Related PRs/Issues
- None

### CODE REVIEW

**Review by NimJay — APPROVED** [review]
Change looks good to me.
I assume we'll eventually remove @Shabirmean from @GoogleCloudPlatform/teams/onyx-gke-observability as the other members start joining.

**Comment by Shabirmean** [comment]
> Change looks good to me. I assume we'll eventually remove @Shabirmean from @GoogleCloudPlatform/onyx-gke-observability as the other members start joining.

Yup makes sense!

**Review by ahrarmonsur — APPROVED** [review]
LGTM! Your approach to adding the appropriate folks to the CODEOWNER team makes sense.

**Comment by leonzz** [comment]
Thanks @Shabirmean! I joined the `GoogleCloudPlatform` org and also sent a request to join GH Team [onyx-observability](https://github.com/orgs/GoogleCloudPlatform/teams/onyx-gke-observability).

**Review by rsgowman — APPROVED** [review]

**Comment by Shabirmean** [comment]
@leonzz - I have accepted your request. I have also made you and @rsgowman as `Maintainer`s of that team and removed myself from there. 

You can continue to add others from your team who work these samples. Also don't forget to update it when someone from the team leaves.

**Pull request merged**
