### PR TITLE
fix: update multi-cloud samples

### PR DESCRIPTION
**Pull request by jiefenghe**
### Fixes ISSUE_NO_HERE
- If you still haven't done yet, then please do create an issue in the repository before opening this PR

#### Description
- Brief description of the issue/purpose of this PR

   Improve the multicloud sample  

- Include environment _(e.g: Linux/Ubuntu running terraform v14.10 etc)_ if relavant

#### Change summary
- Bump cluster version to latest 1.28.3-gke.700 for both AWS and Azure
- Add AWS`iam:GetInstanceProfile` requirement for Anthos Multi-Cloud API service agent role

#### Related PRs/Issues
- List any related PRs and Issues

### CODE REVIEW

**Review by VeraQin — APPROVED** [review]

**Review by apeabody — APPROVED** [review]
Thanks @jiefenghe!

LGTM

**Pull request merged**
