### PR TITLE
test: verify abm installation works

### LINKED ISSUE #194: Check for successful ABM installation in the integration tests
### Description
- Currently the integration tests only cover up to setting up the GCE infrastructure in GCP and configuring the GCE VMs
- It does not validate if the Anthos bare metal installation itself is successfull
- Thus we need to extend the integration tests to verify that the ABM install succeeds
- This will allow us to capture issue like: https://github.com/GoogleCloudPlatform/anthos-samples/issues/158

### PR DESCRIPTION
**Pull request by Shabirmean**
#### Description
- The integration tests that we currently have validates if the GCEs were properly created and whether they were configured with the required tools
- However, it doesn't validate the Anthos bare metal installation itself.
- Thus we need make sure that the test covers the installation step as well

#### Change summary

- Update the integration tests to install Anthos Bare Metal
   - Use  the same commands that is printed out when the terraform script completes running
   - Validate the output from running the install commands against the expected output if the installation succeeded
- The test suite had 2 tests to validate if the script works under two conditions: 
   - Run with `Owner` permissions **&** Run with `Editor and Project IAM Admin` permissions
   - With the introduction of installing ABM in the integration tests, it is going to take very long for a successful run if we do the tests for both these cases on every PR
   -  However, if it works for the latter case then it should definitely work for the former because `Owner` is superset of all roles
   - Thus, I have removed all components related to running the tests with the `Owner` permissions
 
#### Related PRs/Issues
- N/A

### CODE REVIEW

**Comment by Shabirmean** [comment]
@bharathkkb test failure is due to timeout. Can you help identify where to set the timeout value? Is it [somewhere here](https://github.com/GoogleCloudPlatform/anthos-samples/blob/check-abm-install/build/int.cloudbuild.yaml#L24-L46)?

**Comment by bharathkkb** [comment]
@Shabirmean You can add the `-timeout` flag available in go test. Setting `-timeout 0` will do an infinite timeout. This can be added here https://github.com/GoogleCloudPlatform/anthos-samples/blob/c37c0268941fcc85434f0b30d4d31bd4f882207d/build/int.cloudbuild.yaml#L58
`RUN_STAGE=verify go test -v -run TestABMEditor ./... -p 1 -timeout 0`

**Review by bharathkkb — APPROVED** [review]
Looks great! I did notice that some of the ssh commands seemed to not show up via CB UI and but showed up in the raw CB logs
```
[K[2022-03-07 19:45:12+0000] Deleting bootstrap cluster... â ´ 
[K[2022-03-07 19:45:12+0000] Deleting bootstrap cluster... â ¦ 
[K[2022-03-07 19:45:12+0000] Deleting bootstrap cluster... OK
```
Assuming this is because of some progress indicator from the script. Perhaps a flag to turn this off would make it appear in the CB UI.

**Review by ckim328 — APPROVED** [review]
LGTM!

**Pull request merged**
