### PR TITLE
chore: upgrading to bmctl version 1.7 to match the documentation version

### PR DESCRIPTION
**Pull request by Shabirmean**
- Upgrade the `bmctl` version to `1.7.0` since the iX is released for the latest version
- Rename the `preflights.sh` file to `run_initialization_checks.sh` to evade confusion about he preflight checks from the bmctl tool

### CODE REVIEW

**Comment by Shabirmean** [comment]
Required tests `(marked as Waiting for status to be reported)` under the checks section above would never run, because they have not been merged yet. 

We see it here because the checks are picked up _(by name)_ in the settings menu from all open PRs. So when we enable it in the settings, it shows up in all PRs non-merged PRs even before the original one that introduced it is merged

**Comment by dinagraves** [comment]
> Required tests `(marked as Waiting for status to be reported)` under the checks section above would never run, because they have not been merged yet.
> 
> We see it here because the checks are picked up _(by name)_ in the settings menu from all open PRs. So when we enable it in the settings, it shows up in all PRs non-merged PRs even before the original one that introduced it is merged

Should they be marked as optional?  Not required?

**Comment by Shabirmean** [comment]
> > Required tests `(marked as Waiting for status to be reported)` under the checks section above would never run, because they have not been merged yet.
> > We see it here because the checks are picked up _(by name)_ in the settings menu from all open PRs. So when we enable it in the settings, it shows up in all PRs non-merged PRs even before the original one that introduced it is merged
> 
> Should they be marked as optional? Not required?

They should ideally be marked as `Required`. It's just that Github doesn't wait till the actual PRs that introduces the tests is merged. I can remove those tests from the settings until we merge this PR and the [one that adds these labels](https://github.com/GoogleCloudPlatform/anthos-samples/pull/26).

**Comment by Shabirmean** [comment]
@dinagraves - I removed all those tests until the PRs are merged

**Review by dinagraves — APPROVED** [review]

**Pull request merged**
